### ISSUE TITLE
opam-0install-solver appears to select the wrong ocaml

### ISSUE THREAD

**Issue by NathanReb** [ocaml-opam/opam-0install-solver#25] opened 2021-01-21 14:08 UTC
We use opam-0install in `opam-monorepo` and I'm a bit surprised by the following result:
```
[DEBUG] Solver request: ppx_sexp_conv ppxlib
opam-monorepo: 0install diagnostic:
               Can't find all required versions.
               Selected: base.v0.14.1 base-threads.base base-unix.base csexp.1.3.2
                         dune.2.8.1 dune-configurator.2.8.1 ocaml.4.13.0 ocaml-config.2
                         ppx_sexp_conv.zdev result.1.5 sexplib0.v0.14.0 ppx_sexp_conv&ppxlib
                         ocaml-base-compiler ocaml-base-compiler ocaml
               - ocaml-base-compiler -> (problem)
                   Rejected candidates:
                     ocaml-base-compiler.4.12.0~beta1: Requires ocaml = 4.12.0
                     ocaml-base-compiler.4.12.0~alpha3: Requires ocaml = 4.12.0
                     ocaml-base-compiler.4.12.0~alpha2: Requires ocaml = 4.12.0
                     ocaml-base-compiler.4.12.0~alpha1: Requires ocaml = 4.12.0
                     ocaml-base-compiler.4.11.1: Requires ocaml = 4.11.1
                     ...
               - ppxlib -> (problem)
                   Rejected candidates:
                     ppxlib.zdev: Requires ocaml >= 4.04.1 & < 4.13
```
As you can see the solver request (i.e. the argument passed to `solve`) is `ppx_sexp_conv` and `ppxlib`. Those only exist in a single version in the solver context, the local one (we use a custom context wrapping a regular `Switch_context` so that packages present in the folder have a single `zdev` version corresponding to the local opam files).

Given that we ask for `ppxlib` which has an `ocaml < 4.13` bound, I don't understand why the solver would select `4.13` and then reject the only available ppxlib.

Do you have any idea what's going on here?

**Comment by talex5** [comment] 2021-01-21 14:19
If there is no solution, it will pick (what it thinks is) a close approximation and then explain why that doesn't work. In this case, it picked `ocaml.4.13.0` for `ppx_sexp_conv` and then rejected `ppxlib` for the diagnostics.

The easy way to direct it to a better example is to add the version you think it should have chosen to the front of the request. e.g.

```
opam-0install ocaml.4.11.1 ppx_sexp_conv ppxlib
```

Then it will pick an example with OCaml 4.11.1. Keep adding more specific versions like this until it shows the real problem.

**Comment by NathanReb** [comment] 2021-01-21 14:24
Yes but that's not something we can do unfortunately.

The thing here is that a solution exist, e.g. picking any older ocaml version works, I'm able to install both my local ppx_sexp_conv and ppxlib through opam that way. What I'm asking here is why the solver is not seeing it?

**Comment by talex5** [comment] 2021-01-21 14:33
Why can't you do it? Are you running this locally? Wherever you're passing the list of packages to the solver, just add this at the start.

If for some reason you don't have access to the service showing the error, try adding `ocaml = 4.11.1` as the first dependency of `ppx_sexp_conv`.

**Comment by NathanReb** [comment] 2021-01-21 14:48
Sorry, I'm not sure I understand your suggestions. Do you want me to run those for debugging purposes (in which I can and I am happy to do it) or are you suggesting this as a fix?

**Comment by talex5** [comment] 2021-01-21 16:22
Yes, for debugging.

**Comment by talex5** [comment] 2021-02-19 14:46
Closing due to lack of information. If you still believe this is a bug (i.e. that there is a valid solution which it is not finding), please reopen with the output from constraining the OCaml version and, ideally, an example of a valid solution.

**Closed by talex5** 2021-02-19 14:46 UTC

**Comment by NathanReb** [comment] 2021-02-19 15:44
Sorry for the delay, I'll re-open when I have more time to look into it!

**Comment by emillon** [comment] 2021-03-18 13:05
I think this came up in a different project (@craigfe might now more) and the issue is that in the case where there's no solution, the error message might reference a set of constraints that is different from the original constraint.

**Comment by CraigFe** [comment] 2021-03-18 14:26
I think the problem I was observing is more or less exactly what @talex5 describes [above](https://github.com/ocaml-opam/opam-0install-solver/issues/25#issuecomment-764673559), i.e. not a bug.

In Tezos, the selection strategy for picking an installable subset of an uninstallable set of packages / constraints was behaving fairly pathologically. One issue was the solver being keen to pick `ocaml.4.13` and then complain about the (many) packages that were incompatible with it, including `ocaml-base-compiler`:

```
               - ocaml-base-compiler -> (problem)
                   Rejected candidates:
                     ocaml-base-compiler.4.12.0: Requires ocaml = 4.12.0
                     ocaml-base-compiler.4.12.0~rc1: Requires ocaml = 4.12.0
                     ocaml-base-compiler.4.12.0~beta2: Requires ocaml = 4.12.0
                     ocaml-base-compiler.4.12.0~beta1: Requires ocaml = 4.12.0
                     ocaml-base-compiler.4.12.0~alpha3: Requires ocaml = 4.12.0
                     ...
```

In my case, the issue with `ocaml` was part of a larger problem of the solver picking very modern packages and then immediately finding conflicts in related packages. For instance, here it picks `irmin.2.5.0` and then discovers that `irmin-mem` hasn't been installable since `2.3.0`:

```
               - irmin-mem -> (problem)
                   Rejected candidates:
                     irmin-mem.2.3.0: Requires irmin = 2.3.0
                     irmin-mem.2.2.0: Requires irmin >= 2.2.0 & < 2.3.0
                     irmin-mem.2.0.0: Requires irmin >= 2.0.0 & < 2.2.0
                     irmin-mem.1.3.0: Requires irmin >= 1.3.0 & < 2.0.0
                     irmin-mem.1.2.0: Requires irmin >= 1.2.0 & < 1.3.0
```

(The correct choice here is `2.3.0`.) Here's an example of a similar issue in the other direction (selecting a derived package and then failing to install a related dependency):

```
               - cohttp -> (problem)
                   cohttp-lwt 3.0.0 requires = 3.0.0
                   Rejected candidates:
                     cohttp.0.22.0: Doesn't build with dune
                     cohttp.0.21.1: Doesn't build with dune
                     cohttp.0.21.0: Doesn't build with dune
                     cohttp.0.20.2: Doesn't build with dune
                     cohttp.0.20.1: Doesn't build with dune
                     ...
 ```

(The correct choice here is `2.4.5`.) Since Tezos contains quite a lot of this sort of multi-package dependency (including relates PPXes from JS distributions), I needed to specify ~30 versions to see the "real" issues that needed to be solved. These ended up being unrelated, but once I'd solved them I was able to drop the manual constraints and let the solver find the right solution itself.

**Comment by CraigFe** [comment] 2021-03-18 14:54
> I think the problem I was observing is more or less exactly what @talex5 describes [above](https://github.com/ocaml-opam/opam-0install-solver/issues/25#issuecomment-764673559), i.e. not a bug.

To clarify, I think that even if this problem isn't technically a bug, it does seem to be a significant UX issue for big `opam monorepo` deployments like Tezos.

**Comment by talex5** [comment] 2021-03-18 15:04
One option might be to list dependencies you know are likely to require old versions first. e.g. if you list `irmin-mem` before `irmin` then it will treat that as more important when deciding what to show in the diagnostics.
